### ISSUE TITLE
能否加个打开的全局快捷键

### ISSUE THREAD

**Issue by sethyuan** [vipzhicheng/logseq-plugin-pen#1]
非常棒而且非常实用的插件，👍！

是否可以给个全局打开的快捷键配置？最好也可以在命令列表（cmd+shift+p那个）里找到，这样比较方便使用。

**Comment by vipzhicheng** [comment]
嗯，可以先加到命令列表里，快捷键现在太多了，搞不好就跟别人冲突了，现在倾向于支持快捷键但是默认不开启。

**Comment by sethyuan** [comment]
我一般都是给个配置，用户自己配，默认为空，就是没有快捷键。

**Comment by vipzhicheng** [comment]
加上了，默认为空，本地给了个 `cmd+p`
